vcs:
  name: git
  sign-tag: true

version-generator:
  name: semantic
  allow-label: true

version-persister: vcs-tag

prerequisites:
  display-last-changes: ~

pre-release-actions:
  changelog-update:
    format: simple
    file: CHANGELOG.md
    dump-commits: true
  vcs-commit: ~

post-release-actions:
  vcs-publish:
    ask-confirmation: true
